global:
  namespaceOverride: otus-mongodb

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.0-debian-10-r0
  pullPolicy: IfNotPresent
  debug: false

architecture: replicaset
useStatefulSet: true
auth:
  enabled: true
  rootPassword: ""
  replicaSetKey: replicaSetkey
replicaSetName: otustest
replicaSetHostnames: true
initdbScripts:
  my_init_script.js: |
    use test-database
    db.createCollection('${ECOLLECTION}');
    db.createRole(
          {
            role: "myCollAdmin",
            privileges: [
              { resource: { db: "test-database", collection: "${ECOLLECTION}" }, 
              actions: ["find", "update", "insert", "remove"] }
            ],
            roles: [
            ]
          },
          { w: "majority" , wtimeout: 5000 }
        );
    db.createUser({
              user: 'test-user',
              pwd: '${EPASS}',
              roles: [
                {
                  role: 'myCollAdmin',
                  db: 'test-database',
                },
              ],
            });    

replicaCount: 3

resources:
  limits: {}
  requests: 
     cpu: 100m
     memory: 256Mi

persistence:
  enabled: false
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {}
  mountPath: /bitnami/mongodb
  subPath: ""

  
metrics:
  enabled: true
  ## Bitnami MongoDB Promtheus Exporter image
  ## ref: https://hub.docker.com/r/bitnami/mongodb-exporter/tags/
  ##
  image:
    registry: docker.io
    repository: bitnami/mongodb-exporter
    tag: 0.11.2-debian-10-r354
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 9216
